aggregation:
  type: sum
api_version: v1
data_type: numeric
display_name: action_values__offsite_conversion__fb_pixel_initiate_checkout_value
field_type: metric
group: CLI
slug: action_values__offsite_conversion__fb_pixel_initiate_checkout_value
