api_version: v1
data_source: PC_FIVETRAN_DB.FACEBOOK_VIEWS.METRIC_ADS_DAILY_ACTION_VALUES_TRANSFORMED
fields:
- data_reference: '"ADD_PAYMENT_INFO"'
  field_map:
  - action_values__add_payment_info_value
- data_reference: '"ADD_TO_CART"'
  field_map:
  - action_values__add_to_cart_value
- data_reference: '"ADD_TO_WISHLIST"'
  field_map:
  - action_values__add_to_wishlist_value
- data_reference: '"AD_ID"'
  field_map:
  - ad_id
- data_reference: '"APP_CUSTOM_EVENT__FB_MOBILE_ACTIVATE_APP"'
  field_map:
  - action_values__app_custom_event__fb_mobile_activate_app_value
- data_reference: '"APP_CUSTOM_EVENT__FB_MOBILE_ADD_TO_CART"'
  field_map:
  - action_values__app_custom_event__fb_mobile_add_to_cart_value
- data_reference: '"APP_CUSTOM_EVENT__FB_MOBILE_COMPLETE_REGISTRATION"'
  field_map:
  - action_values__app_custom_event__fb_mobile_complete_registration_value
- data_reference: '"APP_CUSTOM_EVENT__FB_MOBILE_INITIATED_CHECKOUT"'
  field_map:
  - action_values__app_custom_event__fb_mobile_initiated_checkout_value
- data_reference: '"APP_CUSTOM_EVENT__FB_MOBILE_PURCHASE"'
  field_map:
  - action_values__app_custom_event__fb_mobile_purchase_value
- data_reference: '"COMMENT"'
  field_map:
  - action_values__comment_value
- data_reference: '"COMPLETE_REGISTRATION"'
  field_map:
  - action_values__complete_registration_value
- data_reference: '"DATE"'
  field_map:
  - date
- data_reference: '"INITIATE_CHECKOUT"'
  field_map:
  - action_values__initiate_checkout_value
- data_reference: '"INTERACTIVE_COMPONENT_TAP"'
  field_map:
  - action_values__interactive_component_tap_value
- data_reference: '"LANDING_PAGE_VIEW"'
  field_map:
  - action_values__landing_page_view_value
- data_reference: '"LIKE"'
  field_map:
  - action_values__like_value
- data_reference: '"LINK_CLICK"'
  field_map:
  - action_values__link_click_value
- data_reference: '"MOBILE_APP_INSTALL"'
  field_map:
  - action_values__mobile_app_install_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_ADD_PAYMENT_INFO"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_add_payment_info_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_ADD_TO_CART"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_add_to_cart_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_ADD_TO_WISHLIST"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_add_to_wishlist_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_COMPLETE_REGISTRATION"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_complete_registration_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_INITIATE_CHECKOUT"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_initiate_checkout_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_PURCHASE"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_purchase_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_SEARCH"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_search_value
- data_reference: '"OFFSITE_CONVERSION__FB_PIXEL_VIEW_CONTENT"'
  field_map:
  - action_values__offsite_conversion__fb_pixel_view_content_value
- data_reference: '"OMNI_ACTIVATE_APP"'
  field_map:
  - action_values__omni_activate_app_value
- data_reference: '"OMNI_ADD_TO_CART"'
  field_map:
  - action_values__omni_add_to_cart_value
- data_reference: '"OMNI_APP_INSTALL"'
  field_map:
  - action_values__omni_app_install_value
- data_reference: '"OMNI_COMPLETE_REGISTRATION"'
  field_map:
  - action_values__omni_complete_registration_value
- data_reference: '"OMNI_INITIATED_CHECKOUT"'
  field_map:
  - action_values__omni_initiated_checkout_value
- data_reference: '"OMNI_PURCHASE"'
  field_map:
  - action_values__omni_purchase_value
- data_reference: '"OMNI_SEARCH"'
  field_map:
  - action_values__omni_search_value
- data_reference: '"OMNI_VIEW_CONTENT"'
  field_map:
  - action_values__omni_view_content_value
- data_reference: '"ONSITE_CONVERSION__MESSAGING_BLOCK"'
  field_map:
  - action_values__onsite_conversion__messaging_block_value
- data_reference: '"ONSITE_CONVERSION__MESSAGING_FIRST_REPLY"'
  field_map:
  - action_values__onsite_conversion__messaging_first_reply_value
- data_reference: '"ONSITE_CONVERSION__POST_SAVE"'
  field_map:
  - action_values__onsite_conversion__post_save_value
- data_reference: '"ONSITE_CONVERSION__VIEW_CONTENT"'
  field_map:
  - action_values__onsite_conversion__view_content_value
- data_reference: '"PAGE_ENGAGEMENT"'
  field_map:
  - action_values__page_engagement_value
- data_reference: '"PHOTO_VIEW"'
  field_map:
  - action_values__photo_view_value
- data_reference: '"POST"'
  field_map:
  - action_values__post_value
- data_reference: '"POST_ENGAGEMENT"'
  field_map:
  - action_values__post_engagement_value
- data_reference: '"POST_REACTION"'
  field_map:
  - action_values__post_reaction_value
- data_reference: '"PURCHASE"'
  field_map:
  - action_values__purchase_value
- data_reference: '"SEARCH"'
  field_map:
  - action_values__search_value
- data_reference: '"VIDEO_VIEW"'
  field_map:
  - action_values__video_view_value
- data_reference: '"VIEW_CONTENT"'
  field_map:
  - action_values__view_content_value
identifiers:
- ad_id
- date
joins:
- join_type: left
  relationship: many_to_one
  fields:
  - ad_id
  to_model: facebook_views.entity_ads
model_name: facebook_views.metric_ads_daily_action_values_transformed
